feat: 삽질 기록... ...
1. docker 내에서 dist 폴더 생성 안됨
2. gateway만 dist가 이상하게 생성됨 (직접 npm run build 했을 경우)

diff --git a/gateway/Dockerfile b/gateway/Dockerfile
--- a/gateway/Dockerfile
+++ b/gateway/Dockerfile
@@ -4,10 +4,13 @@ FROM node:18
 WORKDIR /app
 
 COPY package*.json ./
+COPY tsconfig*.json ./
+COPY libs ./libs
+COPY gateway ./gateway
+
 RUN npm install
 
-COPY . .
+RUN npm run build && echo "✅ Build Success" || echo "❌ Build Failed"
+ # 빌드 실행
 
-RUN npm run build
-
-CMD ["node", "dist/main"]
+CMD ["node", "gateway/dist/main.js"]
